### ISSUE TITLE
Having problems running on fasttext vectors

### ISSUE THREAD

**Issue by patrickdrouin** [yeraidm/meemi#15]
Hello, 

I am trying to test meemi on some fasttext embeddings (in txt format) I have.  Here's the output I get. Any idea what is happening? I suspect it can read the embeddings since the first 2 steps seem to be running just fine. 

(metavirt) $ ./meemi/get_crossembs.sh corpus_en.tag.bin.vec corpus_fr.tag.bin.vec en-fr.txt 
Cross-lingual means
Mean mapping
Traceback (most recent call last):
  File "map_embeddings.py", line 304, in <module>
    main()
  File "map_embeddings.py", line 83, in main
    trg_words, z = embeddings.read(trgfile, dtype=dtype)
  File ".../metavirt/meemi/utils/vecmap/embeddings.py", line 23, in read
    count = int(header[0]) if threshold <= 0 else min(threshold, int(header[0]))
ValueError: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "map_embeddings.py", line 304, in <module>
    main()
  File "map_embeddings.py", line 83, in main
    trg_words, z = embeddings.read(trgfile, dtype=dtype)
  File ".../metavirt/meemi/utils/vecmap/embeddings.py", line 23, in read
    count = int(header[0]) if threshold <= 0 else min(threshold, int(header[0]))
ValueError: invalid literal for int() with base 10: ''

**Comment by patrickdrouin** [comment]
Tested with word2vec embeddings and ran into the same problem.
